apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260513-210243-l8wk76md0cyi-service
spec:
  selector:
    app: enterprise-system-20260513-210243-l8wk76md0cyi
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
